In [1]:
import yfinance as yf
data=yf.download('HDFCBANK.NS',period='7d')
print(data)

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open      Volume
Ticker     HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS HDFCBANK.NS
Date
2026-07-28  735.400024  740.250000  732.000000  732.000000    33886037
2026-07-29  748.200012  751.250000  740.799988  743.000000    20460659
2026-07-30  753.950012  757.900024  745.500000  752.799988    35844392
2026-07-31  748.150024  757.549988  747.200012  753.950012    25522483
2026-08-03  753.000000  756.849976  750.049988  753.049988    14827841
2026-08-04  742.000000  753.200012  738.000000  753.200012    31559802
2026-08-05  735.000000  741.950012  732.599976  733.799988    60031343

In [7]:
data.info()
data.columns
l1=[]
for i in data.columns:
    l1.append(i[0])
data.columns=l1

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 7 entries, 2026-07-28 to 2026-08-05
Data columns (total 5 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   (Close, HDFCBANK.NS)   7 non-null      float64
 1   (High, HDFCBANK.NS)    7 non-null      float64
 2   (Low, HDFCBANK.NS)     7 non-null      float64
 3   (Open, HDFCBANK.NS)    7 non-null      float64
 4   (Volume, HDFCBANK.NS)  7 non-null      int64
dtypes: float64(4), int64(1)
memory usage: 336.0 bytes

In [8]:
data

                 Close        High         Low        Open    Volume
Date
2026-07-28  735.400024  740.250000  732.000000  732.000000  33886037
2026-07-29  748.200012  751.250000  740.799988  743.000000  20460659
2026-07-30  753.950012  757.900024  745.500000  752.799988  35844392
2026-07-31  748.150024  757.549988  747.200012  753.950012  25522483
2026-08-03  753.000000  756.849976  750.049988  753.049988  14827841
2026-08-04  742.000000  753.200012  738.000000  753.200012  31559802
2026-08-05  735.000000  741.950012  732.599976  733.799988  60031343

In [2]:
!pip install pendulum

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pendulum in c:\users\tusha\appdata\roaming\python\python312\site-packages (3.2.0)
Requirement already satisfied: python-dateutil>=2.6 in c:\users\tusha\appdata\roaming\python\python312\site-packages (from pendulum) (2.9.0.post0)
Requirement already satisfied: tzdata>=2020.1 in c:\users\tusha\appdata\roaming\python\python312\site-packages (from pendulum) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\tusha\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.6->pendulum) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pendulum
time_zone='America/New_York'
print(pendulum.now(time_zone))

2026-08-05 13:29:44.136887-04:00

In [4]:
pendulum.timezones()

{'Africa/Abidjan',
 'Africa/Accra',
 'Africa/Addis_Ababa',
 'Africa/Algiers',
 'Africa/Asmara',
 'Africa/Asmera',
 'Africa/Bamako',
 'Africa/Bangui',
 'Africa/Banjul',
 'Africa/Bissau',
 'Africa/Blantyre',
 'Africa/Brazzaville',
 'Africa/Bujumbura',
 'Africa/Cairo',
 'Africa/Casablanca',
 'Africa/Ceuta',
 'Africa/Conakry',
 'Africa/Dakar',
 'Africa/Dar_es_Salaam',
 'Africa/Djibouti',
 'Africa/Douala',
 'Africa/El_Aaiun',
 'Africa/Freetown',
 'Africa/Gaborone',
 'Africa/Harare',
 'Africa/Johannesburg',
 'Africa/Juba',
 'Africa/Kampala',
 'Africa/Khartoum',
 'Africa/Kigali',
 'Africa/Kinshasa',
 'Africa/Lagos',
 'Africa/Libreville',
 'Africa/Lome',
 'Africa/Luanda',
 'Africa/Lubumbashi',
 'Africa/Lusaka',
 'Africa/Malabo',
 'Africa/Maputo',
 'Africa/Maseru',
 'Africa/Mbabane',
 'Africa/Mogadishu',
 'Africa/Monrovia',
 'Africa/Nairobi',
 'Africa/Ndjamena',
 'Africa/Niamey',
 'Africa/Nouakchott',
 'Africa/Ouagadougou',
 'Africa/Porto-Novo',
 'Africa/Sao_Tome',
 'Africa/Timbuktu',
 'Africa/Tripoli',
 'Africa/Tunis',
 'Africa/Windhoek',
 'America/Adak',
 'America/Anchorage',
 'America/Anguilla',
 'America/Antigua',
 'America/Araguaina',
 'America/Argentina/Buenos_Aires',
 'America/Argentina/Catamarca',
 'America/Argentina/ComodRivadavia',
 'America/Argentina/Cordoba',
 'America/Argentina/Jujuy',
 'America/Argentina/La_Rioja',
 'America/Argentina/Mendoza',
 'America/Argentina/Rio_Gallegos',
 'America/Argentina/Salta',
 'America/Argentina/San_Juan',
 'America/Argentina/San_Luis',
 'America/Argentina/Tucuman',
 'America/Argentina/Ushuaia',
 'America/Aruba',
 'America/Asuncion',
 'America/Atikokan',
 'America/Atka',
 'America/Bahia',
 'America/Bahia_Banderas',
 'America/Barbados',
 'America/Belem',
 'America/Belize',
 'America/Blanc-Sablon',
 'America/Boa_Vista',
 'America/Bogota',
 'America/Boise',
 'America/Buenos_Aires',
 'America/Cambridge_Bay',
 'America/Campo_Grande',
 'America/Cancun',
 'America/Caracas',
 'America/Catamarca',
 'America/Cayenne',
 'America/Cayman',
 'America/Chicago',
 'America/Chihuahua',
 'America/Ciudad_Juarez',
 'America/Coral_Harbour',
 'America/Cordoba',
 'America/Costa_Rica',
 'America/Coyhaique',
 'America/Creston',
 'America/Cuiaba',
 'America/Curacao',
 'America/Danmarkshavn',
 'America/Dawson',
 'America/Dawson_Creek',
 'America/Denver',
 'America/Detroit',
 'America/Dominica',
 'America/Edmonton',
 'America/Eirunepe',
 'America/El_Salvador',
 'America/Ensenada',
 'America/Fort_Nelson',
 'America/Fort_Wayne',
 'America/Fortaleza',
 'America/Glace_Bay',
 'America/Godthab',
 'America/Goose_Bay',
 'America/Grand_Turk',
 'America/Grenada',
 'America/Guadeloupe',
 'America/Guatemala',
 'America/Guayaquil',
 'America/Guyana',
 'America/Halifax',
 'America/Havana',
 'America/Hermosillo',
 'America/Indiana/Indianapolis',
 'America/Indiana/Knox',
 'America/Indiana/Marengo',
 'America/Indiana/Petersburg',
 'America/Indiana/Tell_City',
 'America/Indiana/Vevay',
 'America/Indiana/Vincennes',
 'America/Indiana/Winamac',
 'America/Indianapolis',
 'America/Inuvik',
 'America/Iqaluit',
 'America/Jamaica',
 'America/Jujuy',
 'America/Juneau',
 'America/Kentucky/Louisville',
 'America/Kentucky/Monticello',
 'America/Knox_IN',
 'America/Kralendijk',
 'America/La_Paz',
 'America/Lima',
 'America/Los_Angeles',
 'America/Louisville',
 'America/Lower_Princes',
 'America/Maceio',
 'America/Managua',
 'America/Manaus',
 'America/Marigot',
 'America/Martinique',
 'America/Matamoros',
 'America/Mazatlan',
 'America/Mendoza',
 'America/Menominee',
 'America/Merida',
 'America/Metlakatla',
 'America/Mexico_City',
 'America/Miquelon',
 'America/Moncton',
 'America/Monterrey',
 'America/Montevideo',
 'America/Montreal',
 'America/Montserrat',
 'America/Nassau',
 'America/New_York',
 'America/Nipigon',
 'America/Nome',
 'America/Noronha',
 'America/North_Dakota/Beulah',
 'America/North_Dakota/Center',
 'America/North_Dakota/New_Salem',
 'America/Nuuk',
 'America/Ojinaga',
 'America/Panama',
 'America/Pangnirtung',
 'America/Paramaribo',
 'America/Phoenix',
 'America/Port-au-Prince',
 'America/Port_of_Spain',
 'America/Porto_Acre',
 'America/Porto_Velho',
 'America/Puerto_Rico',
 'America/Punta_Arenas',
 'America/Rainy_River',
 'America/Rankin_Inlet',
 'America/Recife',
 'America/Regina',
 'America/Resolute',
 'America/Rio_Branco',
 'America/Rosario',
 'America/Santa_Isabel',
 'America/Santarem',
 'America/Santiago',
 'America/Santo_Domingo',
 'America/Sao_Paulo',
 'America/Scoresbysund',
 'America/Shiprock',
 'America/Sitka',
 'America/St_Barthelemy',
 'America/St_Johns',
 'America/St_Kitts',
 'America/St_Lucia',
 'America/St_Thomas',
 'America/St_Vincent',
 'America/Swift_Current',
 'America/Tegucigalpa',
 'America/Thule',
 'America/Thunder_Bay',
 'America/Tijuana',
 'America/Toronto',
 'America/Tortola',
 'America/Vancouver',
 'America/Virgin',
 'America/Whitehorse',
 'America/Winnipeg',
 'America/Yakutat',
 'America/Yellowknife',
 'Antarctica/Casey',
 'Antarctica/Davis',
 'Antarctica/DumontDUrville',
 'Antarctica/Macquarie',
 'Antarctica/Mawson',
 'Antarctica/McMurdo',
 'Antarctica/Palmer',
 'Antarctica/Rothera',
 'Antarctica/South_Pole',
 'Antarctica/Syowa',
 'Antarctica/Troll',
 'Antarctica/Vostok',
 'Arctic/Longyearbyen',
 'Asia/Aden',
 'Asia/Almaty',
 'Asia/Amman',
 'Asia/Anadyr',
 'Asia/Aqtau',
 'Asia/Aqtobe',
 'Asia/Ashgabat',
 'Asia/Ashkhabad',
 'Asia/Atyrau',
 'Asia/Baghdad',
 'Asia/Bahrain',
 'Asia/Baku',
 'Asia/Bangkok',
 'Asia/Barnaul',
 'Asia/Beirut',
 'Asia/Bishkek',
 'Asia/Brunei',
 'Asia/Calcutta',
 'Asia/Chita',
 'Asia/Choibalsan',
 'Asia/Chongqing',
 'Asia/Chungking',
 'Asia/Colombo',
 'Asia/Dacca',
 'Asia/Damascus',
 'Asia/Dhaka',
 'Asia/Dili',
 'Asia/Dubai',
 'Asia/Dushanbe',
 'Asia/Famagusta',
 'Asia/Gaza',
 'Asia/Harbin',
 'Asia/Hebron',
 'Asia/Ho_Chi_Minh',
 'Asia/Hong_Kong',
 'Asia/Hovd',
 'Asia/Irkutsk',
 'Asia/Istanbul',
 'Asia/Jakarta',
 'Asia/Jayapura',
 'Asia/Jerusalem',
 'Asia/Kabul',
 'Asia/Kamchatka',
 'Asia/Karachi',
 'Asia/Kashgar',
 'Asia/Kathmandu',
 'Asia/Katmandu',
 'Asia/Khandyga',
 'Asia/Kolkata',
 'Asia/Krasnoyarsk',
 'Asia/Kuala_Lumpur',
 'Asia/Kuching',
 'Asia/Kuwait',
 'Asia/Macao',
 'Asia/Macau',
 'Asia/Magadan',
 'Asia/Makassar',
 'Asia/Manila',
 'Asia/Muscat',
 'Asia/Nicosia',
 'Asia/Novokuznetsk',
 'Asia/Novosibirsk',
 'Asia/Omsk',
 'Asia/Oral',
 'Asia/Phnom_Penh',
 'Asia/Pontianak',
 'Asia/Pyongyang',
 'Asia/Qatar',
 'Asia/Qostanay',
 'Asia/Qyzylorda',
 'Asia/Rangoon',
 'Asia/Riyadh',
 'Asia/Saigon',
 'Asia/Sakhalin',
 'Asia/Samarkand',
 'Asia/Seoul',
 'Asia/Shanghai',
 'Asia/Singapore',
 'Asia/Srednekolymsk',
 'Asia/Taipei',
 'Asia/Tashkent',
 'Asia/Tbilisi',
 'Asia/Tehran',
 'Asia/Tel_Aviv',
 'Asia/Thimbu',
 'Asia/Thimphu',
 'Asia/Tokyo',
 'Asia/Tomsk',
 'Asia/Ujung_Pandang',
 'Asia/Ulaanbaatar',
 'Asia/Ulan_Bator',
 'Asia/Urumqi',
 'Asia/Ust-Nera',
 'Asia/Vientiane',
 'Asia/Vladivostok',
 'Asia/Yakutsk',
 'Asia/Yangon',
 'Asia/Yekaterinburg',
 'Asia/Yerevan',
 'Atlantic/Azores',
 'Atlantic/Bermuda',
 'Atlantic/Canary',
 'Atlantic/Cape_Verde',
 'Atlantic/Faeroe',
 'Atlantic/Faroe',
 'Atlantic/Jan_Mayen',
 'Atlantic/Madeira',
 'Atlantic/Reykjavik',
 'Atlantic/South_Georgia',
 'Atlantic/St_Helena',
 'Atlantic/Stanley',
 'Australia/ACT',
 'Australia/Adelaide',
 'Australia/Brisbane',
 'Australia/Broken_Hill',
 'Australia/Canberra',
 'Australia/Currie',
 'Australia/Darwin',
 'Australia/Eucla',
 'Australia/Hobart',
 'Australia/LHI',
 'Australia/Lindeman',
 'Australia/Lord_Howe',
 'Australia/Melbourne',
 'Australia/NSW',
 'Australia/North',
 'Australia/Perth',
 'Australia/Queensland',
 'Australia/South',
 'Australia/Sydney',
 'Australia/Tasmania',
 'Australia/Victoria',
 'Australia/West',
 'Australia/Yancowinna',
 'Brazil/Acre',
 'Brazil/DeNoronha',
 'Brazil/East',
 'Brazil/West',
 'CET',
 'CST6CDT',
 'Canada/Atlantic',
 'Canada/Central',
 'Canada/Eastern',
 'Canada/Mountain',
 'Canada/Newfoundland',
 'Canada/Pacific',
 'Canada/Saskatchewan',
 'Canada/Yukon',
 'Chile/Continental',
 'Chile/EasterIsland',
 'Cuba',
 'EET',
 'EST',
 'EST5EDT',
 'Egypt',
 'Eire',
 'Etc/GMT',
 'Etc/GMT+0',
 'Etc/GMT+1',
 'Etc/GMT+10',
 'Etc/GMT+11',
 'Etc/GMT+12',
 'Etc/GMT+2',
 'Etc/GMT+3',
 'Etc/GMT+4',
 'Etc/GMT+5',
 'Etc/GMT+6',
 'Etc/GMT+7',
 'Etc/GMT+8',
 'Etc/GMT+9',
 'Etc/GMT-0',
 'Etc/GMT-1',
 'Etc/GMT-10',
 'Etc/GMT-11',
 'Etc/GMT-12',
 'Etc/GMT-13',
 'Etc/GMT-14',
 'Etc/GMT-2',
 'Etc/GMT-3',
 'Etc/GMT-4',
 'Etc/GMT-5',
 'Etc/GMT-6',
 'Etc/GMT-7',
 'Etc/GMT-8',
 'Etc/GMT-9',
 'Etc/GMT0',
 'Etc/Greenwich',
 'Etc/UCT',
 'Etc/UTC',
 'Etc/Universal',
 'Etc/Zulu',
 'Europe/Amsterdam',
 'Europe/Andorra',
 'Europe/Astrakhan',
 'Europe/Athens',
 'Europe/Belfast',
 'Europe/Belgrade',
 'Europe/Berlin',
 'Europe/Bratislava',
 'Europe/Brussels',
 'Europe/Bucharest',
 'Europe/Budapest',
 'Europe/Busingen',
 'Europe/Chisinau',
 'Europe/Copenhagen',
 'Europe/Dublin',
 'Europe/Gibraltar',
 'Europe/Guernsey',
 'Europe/Helsinki',
 'Europe/Isle_of_Man',
 'Europe/Istanbul',
 'Europe/Jersey',
 'Europe/Kaliningrad',
 'Europe/Kiev',
 'Europe/Kirov',
 'Europe/Kyiv',
 'Europe/Lisbon',
 'Europe/Ljubljana',
 'Europe/London',
 'Europe/Luxembourg',
 'Europe/Madrid',
 'Europe/Malta',
 'Europe/Mariehamn',
 'Europe/Minsk',
 'Europe/Monaco',
 'Europe/Moscow',
 'Europe/Nicosia',
 'Europe/Oslo',
 'Europe/Paris',
 'Europe/Podgorica',
 'Europe/Prague',
 'Europe/Riga',
 'Europe/Rome',
 'Europe/Samara',
 'Europe/San_Marino',
 'Europe/Sarajevo',
 'Europe/Saratov',
 'Europe/Simferopol',
 'Europe/Skopje',
 'Europe/Sofia',
 'Europe/Stockholm',
 'Europe/Tallinn',
 'Europe/Tirane',
 'Europe/Tiraspol',
 'Europe/Ulyanovsk',
 'Europe/Uzhgorod',
 'Europe/Vaduz',
 'Europe/Vatican',
 'Europe/Vienna',
 'Europe/Vilnius',
 'Europe/Volgograd',
 'Europe/Warsaw',
 'Europe/Zagreb',
 'Europe/Zaporozhye',
 'Europe/Zurich',
 'Factory',
 'GB',
 'GB-Eire',
 'GMT',
 'GMT+0',
 'GMT-0',
 'GMT0',
 'Greenwich',
 'HST',
 'Hongkong',
 'Iceland',
 'Indian/Antananarivo',
 'Indian/Chagos',
 'Indian/Christmas',
 'Indian/Cocos',
 'Indian/Comoro',
 'Indian/Kerguelen',
 'Indian/Mahe',
 'Indian/Maldives',
 'Indian/Mauritius',
 'Indian/Mayotte',
 'Indian/Reunion',
 'Iran',
 'Israel',
 'Jamaica',
 'Japan',
 'Kwajalein',
 'Libya',
 'MET',
 'MST',
 'MST7MDT',
 'Mexico/BajaNorte',
 'Mexico/BajaSur',
 'Mexico/General',
 'NZ',
 'NZ-CHAT',
 'Navajo',
 'PRC',
 'PST8PDT',
 'Pacific/Apia',
 'Pacific/Auckland',
 'Pacific/Bougainville',
 'Pacific/Chatham',
 'Pacific/Chuuk',
 'Pacific/Easter',
 'Pacific/Efate',
 'Pacific/Enderbury',
 'Pacific/Fakaofo',
 'Pacific/Fiji',
 'Pacific/Funafuti',
 'Pacific/Galapagos',
 'Pacific/Gambier',
 'Pacific/Guadalcanal',
 'Pacific/Guam',
 'Pacific/Honolulu',
 'Pacific/Johnston',
 'Pacific/Kanton',
 'Pacific/Kiritimati',
 'Pacific/Kosrae',
 'Pacific/Kwajalein',
 'Pacific/Majuro',
 'Pacific/Marquesas',
 'Pacific/Midway',
 'Pacific/Nauru',
 'Pacific/Niue',
 'Pacific/Norfolk',
 'Pacific/Noumea',
 'Pacific/Pago_Pago',
 'Pacific/Palau',
 'Pacific/Pitcairn',
 'Pacific/Pohnpei',
 'Pacific/Ponape',
 'Pacific/Port_Moresby',
 'Pacific/Rarotonga',
 'Pacific/Saipan',
 'Pacific/Samoa',
 'Pacific/Tahiti',
 'Pacific/Tarawa',
 'Pacific/Tongatapu',
 'Pacific/Truk',
 'Pacific/Wake',
 'Pacific/Wallis',
 'Pacific/Yap',
 'Poland',
 'Portugal',
 'ROC',
 'ROK',
 'Singapore',
 'Turkey',
 'UCT',
 'US/Alaska',
 'US/Aleutian',
 'US/Arizona',
 'US/Central',
 'US/East-Indiana',
 'US/Eastern',
 'US/Hawaii',
 'US/Indiana-Starke',
 'US/Michigan',
 'US/Mountain',
 'US/Pacific',
 'US/Samoa',
 'UTC',
 'Universal',
 'W-SU',
 'WET',
 'Zulu'}

list comprehension

In [2]:
import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average" 
""

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print(response.status_code)

tables = pd.read_html(response.text)
data1=tables[1]
data1

200

C:\Users\tusha\AppData\Local\Temp\ipykernel_25320\3744183405.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

,Company,Exchange,Symbol,Sector,Date added,Notes,Index weighting
0,3M,NYSE,MMM,Industrials,1976-08-09,As Minnesota Mining and Manufacturing,1.85%
1,Alphabet (Class A),NASDAQ,GOOGL,Communication Services,2026-06-29,NaN,4.03%
2,American Express,NYSE,AXP,Financials,1982-08-30,NaN,3.88%
3,Amgen,NASDAQ,AMGN,Health Care,2020-08-31,NaN,4.11%
4,Amazon,NASDAQ,AMZN,Consumer Discretionary,2024-02-26,NaN,2.74%
5,Apple,NASDAQ,AAPL,Information Technology,2015-03-19,NaN,3.21%
6,Boeing,NYSE,BA,Industrials,1987-03-12,NaN,2.45%
7,Caterpillar,NYSE,CAT,Industrials,1991-05-06,NaN,11.77%
8,Chevron,NYSE,CVX,Energy,2008-02-19,Also 1930-07-18 to 1999-11-01,1.92%
9,Cisco,NASDAQ,CSCO,Information Technology,2009-06-08,NaN,1.34%
10,Coca-Cola,NYSE,KO,Consumer Staples,1987-03-12,Also 1932-05-26 to 1935-11-20,0.94%
11,Disney,NYSE,DIS,Communication Services,1991-05-06,NaN,1.12%
12,Goldman Sachs,NYSE,GS,Financials,2013-09-23,NaN,11.62%
13,Home Depot,NYSE,HD,Consumer Discretionary,1999-11-01,NaN,4.00%
14,Honeywell Technologies,NASDAQ,HON,Industrials,2020-08-31,AlliedSignal and Honeywell,2.59%
15,IBM,NYSE,IBM,Information Technology,1979-06-29,Also 1932-05-26 to 1939-03-04,3.17%
16,Johnson & Johnson,NYSE,JNJ,Health Care,1997-03-17,NaN,2.94%
17,JPMorgan Chase,NYSE,JPM,Financials,1991-05-06,NaN,3.75%
18,McDonald's,NYSE,MCD,Consumer Discretionary,1985-10-30,NaN,3.04%
19,Merck,NYSE,MRK,Health Care,1979-06-29,NaN,1.47%
20,Microsoft,NASDAQ,MSFT,Information Technology,1999-11-01,NaN,4.20%
21,Nike,NYSE,NKE,Consumer Discretionary,2013-09-23,NaN,0.47%
22,Nvidia,NASDAQ,NVDA,Information Technology,2024-11-08,NaN,2.22%
23,Procter & Gamble,NYSE,PG,Consumer Staples,1932-05-26,NaN,1.69%
24,Salesforce,NYSE,CRM,Information Technology,2020-08-31,NaN,1.80%
25,Sherwin-Williams,NYSE,SHW,Materials,2024-11-08,NaN,3.92%
26,Travelers,NYSE,TRV,Financials,2009-06-08,NaN,3.78%
27,UnitedHealth Group,NYSE,UNH,Health Care,2012-09-24,NaN,4.78%
28,Visa,NYSE,V,Financials,2013-09-23,NaN,3.89%
29,Walmart,NASDAQ,WMT,Consumer Staples,1997-03-17,NaN,1.31%

In [11]:
data1['Date added']=pd.to_datetime(data1['Date added'])
data1

,Company,Exchange,Symbol,Sector,Date added,Notes,Index weighting
0,3M,NYSE,MMM,Industrials,1976-08-09,As Minnesota Mining and Manufacturing,1.85%
1,Alphabet (Class A),NASDAQ,GOOGL,Communication Services,2026-06-29,NaN,4.03%
2,American Express,NYSE,AXP,Financials,1982-08-30,NaN,3.88%
3,Amgen,NASDAQ,AMGN,Health Care,2020-08-31,NaN,4.11%
4,Amazon,NASDAQ,AMZN,Consumer Discretionary,2024-02-26,NaN,2.74%
5,Apple,NASDAQ,AAPL,Information Technology,2015-03-19,NaN,3.21%
6,Boeing,NYSE,BA,Industrials,1987-03-12,NaN,2.45%
7,Caterpillar,NYSE,CAT,Industrials,1991-05-06,NaN,11.77%
8,Chevron,NYSE,CVX,Energy,2008-02-19,Also 1930-07-18 to 1999-11-01,1.92%
9,Cisco,NASDAQ,CSCO,Information Technology,2009-06-08,NaN,1.34%
10,Coca-Cola,NYSE,KO,Consumer Staples,1987-03-12,Also 1932-05-26 to 1935-11-20,0.94%
11,Disney,NYSE,DIS,Communication Services,1991-05-06,NaN,1.12%
12,Goldman Sachs,NYSE,GS,Financials,2013-09-23,NaN,11.62%
13,Home Depot,NYSE,HD,Consumer Discretionary,1999-11-01,NaN,4.00%
14,Honeywell Technologies,NASDAQ,HON,Industrials,2020-08-31,AlliedSignal and Honeywell,2.59%
15,IBM,NYSE,IBM,Information Technology,1979-06-29,Also 1932-05-26 to 1939-03-04,3.17%
16,Johnson & Johnson,NYSE,JNJ,Health Care,1997-03-17,NaN,2.94%
17,JPMorgan Chase,NYSE,JPM,Financials,1991-05-06,NaN,3.75%
18,McDonald's,NYSE,MCD,Consumer Discretionary,1985-10-30,NaN,3.04%
19,Merck,NYSE,MRK,Health Care,1979-06-29,NaN,1.47%
20,Microsoft,NASDAQ,MSFT,Information Technology,1999-11-01,NaN,4.20%
21,Nike,NYSE,NKE,Consumer Discretionary,2013-09-23,NaN,0.47%
22,Nvidia,NASDAQ,NVDA,Information Technology,2024-11-08,NaN,2.22%
23,Procter & Gamble,NYSE,PG,Consumer Staples,1932-05-26,NaN,1.69%
24,Salesforce,NYSE,CRM,Information Technology,2020-08-31,NaN,1.80%
25,Sherwin-Williams,NYSE,SHW,Materials,2024-11-08,NaN,3.92%
26,Travelers,NYSE,TRV,Financials,2009-06-08,NaN,3.78%
27,UnitedHealth Group,NYSE,UNH,Health Care,2012-09-24,NaN,4.78%
28,Visa,NYSE,V,Financials,2013-09-23,NaN,3.89%
29,Walmart,NASDAQ,WMT,Consumer Staples,1997-03-17,NaN,1.31%

In [15]:
data1['year']=data1['Date added'].dt.year.astype('str')
data1['Sector']=data1['Sector'].str.upper()
data1

,Company,Exchange,Symbol,Sector,Date added,Notes,Index weighting,year
0,3M,NYSE,MMM,INDUSTRIALS,1976-08-09,As Minnesota Mining and Manufacturing,1.85%,1976
1,Alphabet (Class A),NASDAQ,GOOGL,COMMUNICATION SERVICES,2026-06-29,NaN,4.03%,2026
2,American Express,NYSE,AXP,FINANCIALS,1982-08-30,NaN,3.88%,1982
3,Amgen,NASDAQ,AMGN,HEALTH CARE,2020-08-31,NaN,4.11%,2020
4,Amazon,NASDAQ,AMZN,CONSUMER DISCRETIONARY,2024-02-26,NaN,2.74%,2024
5,Apple,NASDAQ,AAPL,INFORMATION TECHNOLOGY,2015-03-19,NaN,3.21%,2015
6,Boeing,NYSE,BA,INDUSTRIALS,1987-03-12,NaN,2.45%,1987
7,Caterpillar,NYSE,CAT,INDUSTRIALS,1991-05-06,NaN,11.77%,1991
8,Chevron,NYSE,CVX,ENERGY,2008-02-19,Also 1930-07-18 to 1999-11-01,1.92%,2008
9,Cisco,NASDAQ,CSCO,INFORMATION TECHNOLOGY,2009-06-08,NaN,1.34%,2009
10,Coca-Cola,NYSE,KO,CONSUMER STAPLES,1987-03-12,Also 1932-05-26 to 1935-11-20,0.94%,1987
11,Disney,NYSE,DIS,COMMUNICATION SERVICES,1991-05-06,NaN,1.12%,1991
12,Goldman Sachs,NYSE,GS,FINANCIALS,2013-09-23,NaN,11.62%,2013
13,Home Depot,NYSE,HD,CONSUMER DISCRETIONARY,1999-11-01,NaN,4.00%,1999
14,Honeywell Technologies,NASDAQ,HON,INDUSTRIALS,2020-08-31,AlliedSignal and Honeywell,2.59%,2020
15,IBM,NYSE,IBM,INFORMATION TECHNOLOGY,1979-06-29,Also 1932-05-26 to 1939-03-04,3.17%,1979
16,Johnson & Johnson,NYSE,JNJ,HEALTH CARE,1997-03-17,NaN,2.94%,1997
17,JPMorgan Chase,NYSE,JPM,FINANCIALS,1991-05-06,NaN,3.75%,1991
18,McDonald's,NYSE,MCD,CONSUMER DISCRETIONARY,1985-10-30,NaN,3.04%,1985
19,Merck,NYSE,MRK,HEALTH CARE,1979-06-29,NaN,1.47%,1979
20,Microsoft,NASDAQ,MSFT,INFORMATION TECHNOLOGY,1999-11-01,NaN,4.20%,1999
21,Nike,NYSE,NKE,CONSUMER DISCRETIONARY,2013-09-23,NaN,0.47%,2013
22,Nvidia,NASDAQ,NVDA,INFORMATION TECHNOLOGY,2024-11-08,NaN,2.22%,2024
23,Procter & Gamble,NYSE,PG,CONSUMER STAPLES,1932-05-26,NaN,1.69%,1932
24,Salesforce,NYSE,CRM,INFORMATION TECHNOLOGY,2020-08-31,NaN,1.80%,2020
25,Sherwin-Williams,NYSE,SHW,MATERIALS,2024-11-08,NaN,3.92%,2024
26,Travelers,NYSE,TRV,FINANCIALS,2009-06-08,NaN,3.78%,2009
27,UnitedHealth Group,NYSE,UNH,HEALTH CARE,2012-09-24,NaN,4.78%,2012
28,Visa,NYSE,V,FINANCIALS,2013-09-23,NaN,3.89%,2013
29,Walmart,NASDAQ,WMT,CONSUMER STAPLES,1997-03-17,NaN,1.31%,1997