In [14]:
!pip3 install lxml

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lxml in c:\users\tusha\appdata\roaming\python\python312\site-packages (6.0.2)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [15]:
!pip3 install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in c:\users\tusha\appdata\roaming\python\python312\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\tusha\appdata\roaming\python\python312\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [16]:
!pip3 install html5lib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: html5lib in c:\users\tusha\appdata\roaming\python\python312\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\tusha\appdata\roaming\python\python312\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\tusha\appdata\roaming\python\python312\site-packages (from html5lib) (0.5.1)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [17]:
!pip3 install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\tusha\appdata\roaming\python\python312\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\tusha\appdata\roaming\python\python312\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tusha\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\tusha\appdata\roaming\python\python312\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\tusha\appdata\roaming\python\python312\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\tusha\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [18]:
!pip3 install requests

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in c:\users\tusha\appdata\roaming\python\python312\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\tusha\appdata\roaming\python\python312\site-packages (from requests) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tusha\appdata\roaming\python\python312\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\tusha\appdata\roaming\python\python312\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tusha\appdata\roaming\python\python312\site-packages (from requests) (2026.2.25)

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [19]:
import pandas as pd
import requests
url = 'https://en.wikipedia.org/wiki/NIFTY_50'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

response = requests.get(url, headers=headers)
df7 = pd.read_html(response.text)
data1=df7[1]
data1

C:\Users\tusha\AppData\Local\Temp\ipykernel_24324\922224212.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df7 = pd.read_html(response.text)

,Company name,Symbol,Sector[15],Date added[16]
0,Adani Enterprises,ADANIENT,Metals & Mining,30 September 2022
1,Adani Ports & SEZ,ADANIPORTS,Services,28 September 2015
2,Apollo Hospitals,APOLLOHOSP,Healthcare,31 March 2022
3,Asian Paints,ASIANPAINT,Consumer Durables,27 April 2012[a]
4,Axis Bank,AXISBANK,Financial Services,27 March 2009
5,Bajaj Auto,BAJAJ-AUTO,Automobile and Auto Components,1 October 2010[b]
6,Bajaj Finance,BAJFINANCE,Financial Services,29 September 2017
7,Bajaj Finserv,BAJAJFINSV,Financial Services,2 April 2018
8,Bharat Electronics,BEL,Capital Goods,30 September 2024
9,Bharti Airtel,BHARTIARTL,Telecommunication,1 March 2004
10,Cipla,CIPLA,Healthcare,7 October 1998
11,Coal India,COALINDIA,"Oil, Gas & Consumable Fuels",10 October 2011
12,Dr. Reddy's Laboratories,DRREDDY,Healthcare,1 October 2010[c]
13,Eicher Motors,EICHERMOT,Automobile and Auto Components,1 April 2016
14,Eternal,ETERNAL,Consumer Services,28 March 2025
15,Grasim Industries,GRASIM,Construction Materials,2 April 2018[d]
16,HCLTech,HCLTECH,Information Technology,28 October 2002
17,HDFC Bank,HDFCBANK,Financial Services,22 April 1996
18,HDFC Life,HDFCLIFE,Financial Services,31 July 2020
19,Hindalco Industries,HINDALCO,Metals & Mining,22 April 1996
20,Hindustan Unilever,HINDUNILVR,Fast Moving Consumer Goods,22 April 1996
21,ICICI Bank,ICICIBANK,Financial Services,25 January 2002
22,IndiGo,INDIGO,Services,30 September 2025
23,Infosys,INFY,Information Technology,7 October 1998
24,ITC,ITC,Fast Moving Consumer Goods,22 April 1996
25,Jio Financial Services,JIOFIN,Financial Services,28 March 2025
26,JSW Steel,JSWSTEEL,Metals & Mining,28 September 2018
27,Kotak Mahindra Bank,KOTAKBANK,Financial Services,8 April 2010
28,Larsen & Toubro,LT,Construction,10 December 2004[e]
29,Mahindra & Mahindra,M&M,Automobile and Auto Components,18 September 1996
30,Maruti Suzuki,MARUTI,Automobile and Auto Components,1 March 2004
31,Max Healthcare,MAXHEALTH,Healthcare,30 September 2025
32,Nestlé India,NESTLEIND,Fast Moving Consumer Goods,27 September 2019[f]
33,NTPC,NTPC,Power,24 September 2007
34,Oil and Natural Gas Corporation,ONGC,"Oil, Gas & Consumable Fuels",12 April 2004
35,Power Grid,POWERGRID,Power,14 March 2008
36,Reliance Industries,RELIANCE,"Oil, Gas & Consumable Fuels",22 April 1996
37,SBI Life Insurance Company,SBILIFE,Financial Services,25 September 2020
38,Shriram Finance,SHRIRAMFIN,Financial Services,28 March 2024
39,State Bank of India,SBIN,Financial Services,22 April 1996
40,Sun Pharma,SUNPHARMA,Healthcare,17 January 2002
41,Tata Consultancy Services,TCS,Information Technology,25 February 2005
42,Tata Consumer Products,TATACONSUM,Fast Moving Consumer Goods,31 March 2021[g]
43,Tata Motors Passenger Vehicles,TMPV,Automobile and Auto Components,22 April 1996
44,Tata Steel,TATASTEEL,Metals & Mining,22 April 1996
45,Tech Mahindra,TECHM,Information Technology,28 March 2014
46,Titan Company,TITAN,Consumer Durables,2 April 2018
47,Trent,TRENT,Consumer Services,30 September 2024
48,UltraTech Cement,ULTRACEMCO,Construction Materials,28 September 2012
49,Wipro,WIPRO,Information Technology,27 September 2013[h]

In [20]:
data1.columns=['name','symbol','sector','data']
data1

,name,symbol,sector,data
0,Adani Enterprises,ADANIENT,Metals & Mining,30 September 2022
1,Adani Ports & SEZ,ADANIPORTS,Services,28 September 2015
2,Apollo Hospitals,APOLLOHOSP,Healthcare,31 March 2022
3,Asian Paints,ASIANPAINT,Consumer Durables,27 April 2012[a]
4,Axis Bank,AXISBANK,Financial Services,27 March 2009
5,Bajaj Auto,BAJAJ-AUTO,Automobile and Auto Components,1 October 2010[b]
6,Bajaj Finance,BAJFINANCE,Financial Services,29 September 2017
7,Bajaj Finserv,BAJAJFINSV,Financial Services,2 April 2018
8,Bharat Electronics,BEL,Capital Goods,30 September 2024
9,Bharti Airtel,BHARTIARTL,Telecommunication,1 March 2004
10,Cipla,CIPLA,Healthcare,7 October 1998
11,Coal India,COALINDIA,"Oil, Gas & Consumable Fuels",10 October 2011
12,Dr. Reddy's Laboratories,DRREDDY,Healthcare,1 October 2010[c]
13,Eicher Motors,EICHERMOT,Automobile and Auto Components,1 April 2016
14,Eternal,ETERNAL,Consumer Services,28 March 2025
15,Grasim Industries,GRASIM,Construction Materials,2 April 2018[d]
16,HCLTech,HCLTECH,Information Technology,28 October 2002
17,HDFC Bank,HDFCBANK,Financial Services,22 April 1996
18,HDFC Life,HDFCLIFE,Financial Services,31 July 2020
19,Hindalco Industries,HINDALCO,Metals & Mining,22 April 1996
20,Hindustan Unilever,HINDUNILVR,Fast Moving Consumer Goods,22 April 1996
21,ICICI Bank,ICICIBANK,Financial Services,25 January 2002
22,IndiGo,INDIGO,Services,30 September 2025
23,Infosys,INFY,Information Technology,7 October 1998
24,ITC,ITC,Fast Moving Consumer Goods,22 April 1996
25,Jio Financial Services,JIOFIN,Financial Services,28 March 2025
26,JSW Steel,JSWSTEEL,Metals & Mining,28 September 2018
27,Kotak Mahindra Bank,KOTAKBANK,Financial Services,8 April 2010
28,Larsen & Toubro,LT,Construction,10 December 2004[e]
29,Mahindra & Mahindra,M&M,Automobile and Auto Components,18 September 1996
30,Maruti Suzuki,MARUTI,Automobile and Auto Components,1 March 2004
31,Max Healthcare,MAXHEALTH,Healthcare,30 September 2025
32,Nestlé India,NESTLEIND,Fast Moving Consumer Goods,27 September 2019[f]
33,NTPC,NTPC,Power,24 September 2007
34,Oil and Natural Gas Corporation,ONGC,"Oil, Gas & Consumable Fuels",12 April 2004
35,Power Grid,POWERGRID,Power,14 March 2008
36,Reliance Industries,RELIANCE,"Oil, Gas & Consumable Fuels",22 April 1996
37,SBI Life Insurance Company,SBILIFE,Financial Services,25 September 2020
38,Shriram Finance,SHRIRAMFIN,Financial Services,28 March 2024
39,State Bank of India,SBIN,Financial Services,22 April 1996
40,Sun Pharma,SUNPHARMA,Healthcare,17 January 2002
41,Tata Consultancy Services,TCS,Information Technology,25 February 2005
42,Tata Consumer Products,TATACONSUM,Fast Moving Consumer Goods,31 March 2021[g]
43,Tata Motors Passenger Vehicles,TMPV,Automobile and Auto Components,22 April 1996
44,Tata Steel,TATASTEEL,Metals & Mining,22 April 1996
45,Tech Mahindra,TECHM,Information Technology,28 March 2014
46,Titan Company,TITAN,Consumer Durables,2 April 2018
47,Trent,TRENT,Consumer Services,30 September 2024
48,UltraTech Cement,ULTRACEMCO,Construction Materials,28 September 2012
49,Wipro,WIPRO,Information Technology,27 September 2013[h]

In [21]:
data1=data1.set_index('name')
data1

,symbol,sector,data
name,,,
Adani Enterprises,ADANIENT,Metals & Mining,30 September 2022
Adani Ports & SEZ,ADANIPORTS,Services,28 September 2015
Apollo Hospitals,APOLLOHOSP,Healthcare,31 March 2022
Asian Paints,ASIANPAINT,Consumer Durables,27 April 2012[a]
Axis Bank,AXISBANK,Financial Services,27 March 2009
Bajaj Auto,BAJAJ-AUTO,Automobile and Auto Components,1 October 2010[b]
Bajaj Finance,BAJFINANCE,Financial Services,29 September 2017
Bajaj Finserv,BAJAJFINSV,Financial Services,2 April 2018
Bharat Electronics,BEL,Capital Goods,30 September 2024
Bharti Airtel,BHARTIARTL,Telecommunication,1 March 2004
Cipla,CIPLA,Healthcare,7 October 1998
Coal India,COALINDIA,"Oil, Gas & Consumable Fuels",10 October 2011
Dr. Reddy's Laboratories,DRREDDY,Healthcare,1 October 2010[c]
Eicher Motors,EICHERMOT,Automobile and Auto Components,1 April 2016
Eternal,ETERNAL,Consumer Services,28 March 2025
Grasim Industries,GRASIM,Construction Materials,2 April 2018[d]
HCLTech,HCLTECH,Information Technology,28 October 2002
HDFC Bank,HDFCBANK,Financial Services,22 April 1996
HDFC Life,HDFCLIFE,Financial Services,31 July 2020
Hindalco Industries,HINDALCO,Metals & Mining,22 April 1996
Hindustan Unilever,HINDUNILVR,Fast Moving Consumer Goods,22 April 1996
ICICI Bank,ICICIBANK,Financial Services,25 January 2002
IndiGo,INDIGO,Services,30 September 2025
Infosys,INFY,Information Technology,7 October 1998
ITC,ITC,Fast Moving Consumer Goods,22 April 1996
Jio Financial Services,JIOFIN,Financial Services,28 March 2025
JSW Steel,JSWSTEEL,Metals & Mining,28 September 2018
Kotak Mahindra Bank,KOTAKBANK,Financial Services,8 April 2010
Larsen & Toubro,LT,Construction,10 December 2004[e]
Mahindra & Mahindra,M&M,Automobile and Auto Components,18 September 1996
Maruti Suzuki,MARUTI,Automobile and Auto Components,1 March 2004
Max Healthcare,MAXHEALTH,Healthcare,30 September 2025
Nestlé India,NESTLEIND,Fast Moving Consumer Goods,27 September 2019[f]
NTPC,NTPC,Power,24 September 2007
Oil and Natural Gas Corporation,ONGC,"Oil, Gas & Consumable Fuels",12 April 2004
Power Grid,POWERGRID,Power,14 March 2008
Reliance Industries,RELIANCE,"Oil, Gas & Consumable Fuels",22 April 1996
SBI Life Insurance Company,SBILIFE,Financial Services,25 September 2020
Shriram Finance,SHRIRAMFIN,Financial Services,28 March 2024
State Bank of India,SBIN,Financial Services,22 April 1996
Sun Pharma,SUNPHARMA,Healthcare,17 January 2002
Tata Consultancy Services,TCS,Information Technology,25 February 2005
Tata Consumer Products,TATACONSUM,Fast Moving Consumer Goods,31 March 2021[g]
Tata Motors Passenger Vehicles,TMPV,Automobile and Auto Components,22 April 1996
Tata Steel,TATASTEEL,Metals & Mining,22 April 1996
Tech Mahindra,TECHM,Information Technology,28 March 2014
Titan Company,TITAN,Consumer Durables,2 April 2018
Trent,TRENT,Consumer Services,30 September 2024
UltraTech Cement,ULTRACEMCO,Construction Materials,28 September 2012
Wipro,WIPRO,Information Technology,27 September 2013[h]

In [23]:
data1.reset_index(inplace=True)
data1.set_index('name',inplace=True)
data1

,symbol,sector,data
name,,,
Adani Enterprises,ADANIENT,Metals & Mining,30 September 2022
Adani Ports & SEZ,ADANIPORTS,Services,28 September 2015
Apollo Hospitals,APOLLOHOSP,Healthcare,31 March 2022
Asian Paints,ASIANPAINT,Consumer Durables,27 April 2012[a]
Axis Bank,AXISBANK,Financial Services,27 March 2009
Bajaj Auto,BAJAJ-AUTO,Automobile and Auto Components,1 October 2010[b]
Bajaj Finance,BAJFINANCE,Financial Services,29 September 2017
Bajaj Finserv,BAJAJFINSV,Financial Services,2 April 2018
Bharat Electronics,BEL,Capital Goods,30 September 2024
Bharti Airtel,BHARTIARTL,Telecommunication,1 March 2004
Cipla,CIPLA,Healthcare,7 October 1998
Coal India,COALINDIA,"Oil, Gas & Consumable Fuels",10 October 2011
Dr. Reddy's Laboratories,DRREDDY,Healthcare,1 October 2010[c]
Eicher Motors,EICHERMOT,Automobile and Auto Components,1 April 2016
Eternal,ETERNAL,Consumer Services,28 March 2025
Grasim Industries,GRASIM,Construction Materials,2 April 2018[d]
HCLTech,HCLTECH,Information Technology,28 October 2002
HDFC Bank,HDFCBANK,Financial Services,22 April 1996
HDFC Life,HDFCLIFE,Financial Services,31 July 2020
Hindalco Industries,HINDALCO,Metals & Mining,22 April 1996
Hindustan Unilever,HINDUNILVR,Fast Moving Consumer Goods,22 April 1996
ICICI Bank,ICICIBANK,Financial Services,25 January 2002
IndiGo,INDIGO,Services,30 September 2025
Infosys,INFY,Information Technology,7 October 1998
ITC,ITC,Fast Moving Consumer Goods,22 April 1996
Jio Financial Services,JIOFIN,Financial Services,28 March 2025
JSW Steel,JSWSTEEL,Metals & Mining,28 September 2018
Kotak Mahindra Bank,KOTAKBANK,Financial Services,8 April 2010
Larsen & Toubro,LT,Construction,10 December 2004[e]
Mahindra & Mahindra,M&M,Automobile and Auto Components,18 September 1996
Maruti Suzuki,MARUTI,Automobile and Auto Components,1 March 2004
Max Healthcare,MAXHEALTH,Healthcare,30 September 2025
Nestlé India,NESTLEIND,Fast Moving Consumer Goods,27 September 2019[f]
NTPC,NTPC,Power,24 September 2007
Oil and Natural Gas Corporation,ONGC,"Oil, Gas & Consumable Fuels",12 April 2004
Power Grid,POWERGRID,Power,14 March 2008
Reliance Industries,RELIANCE,"Oil, Gas & Consumable Fuels",22 April 1996
SBI Life Insurance Company,SBILIFE,Financial Services,25 September 2020
Shriram Finance,SHRIRAMFIN,Financial Services,28 March 2024
State Bank of India,SBIN,Financial Services,22 April 1996
Sun Pharma,SUNPHARMA,Healthcare,17 January 2002
Tata Consultancy Services,TCS,Information Technology,25 February 2005
Tata Consumer Products,TATACONSUM,Fast Moving Consumer Goods,31 March 2021[g]
Tata Motors Passenger Vehicles,TMPV,Automobile and Auto Components,22 April 1996
Tata Steel,TATASTEEL,Metals & Mining,22 April 1996
Tech Mahindra,TECHM,Information Technology,28 March 2014
Titan Company,TITAN,Consumer Durables,2 April 2018
Trent,TRENT,Consumer Services,30 September 2024
UltraTech Cement,ULTRACEMCO,Construction Materials,28 September 2012
Wipro,WIPRO,Information Technology,27 September 2013[h]