In [4]:
import pandas as pd
import requests
url = 'https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

response = requests.get(url, headers=headers)
df1 = pd.read_html(response.text)
data=df1[2]
data

C:\Users\tusha\AppData\Local\Temp\ipykernel_12792\1551809168.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df1 = pd.read_html(response.text)

,Company,Exchange,Symbol,Industry,Date added,Notes,Index weighting
0,3M,NYSE,MMM,Conglomerate,1976-08-09,As Minnesota Mining and Manufacturing,2.17%
1,American Express,NYSE,AXP,Financial services,1982-08-30,NaN,4.31%
2,Amgen,NASDAQ,AMGN,Biopharmaceutical,2020-08-31,NaN,4.14%
3,Amazon,NASDAQ,AMZN,Retailing,2024-02-26,NaN,2.99%
4,Apple,NASDAQ,AAPL,Information technology,2015-03-19,NaN,2.92%
5,Boeing,NYSE,BA,Aerospace and defense,1987-03-12,NaN,3.03%
6,Caterpillar,NYSE,CAT,Construction and mining,1991-05-06,NaN,5.13%
7,Chevron,NYSE,CVX,Petroleum industry,2008-02-19,Also 1930-07-18 to 1999-11-01,2.01%
8,Cisco,NASDAQ,CSCO,Information technology,2009-06-08,NaN,0.92%
9,Coca-Cola,NYSE,KO,Drink industry,1987-03-12,Also 1932-05-26 to 1935-11-20,1.04%
10,Disney,NYSE,DIS,Broadcasting and entertainment,1991-05-06,NaN,1.63%
11,Goldman Sachs,NYSE,GS,Financial services,2013-09-23,NaN,8.79%
12,Home Depot,NYSE,HD,Home Improvement,1999-11-01,NaN,5.35%
13,Honeywell,NASDAQ,HON,Conglomerate,2020-08-31,AlliedSignal and Honeywell,3.27%
14,IBM,NYSE,IBM,Information technology,1979-06-29,Also 1932-05-26 to 1939-03-04,3.77%
15,Johnson & Johnson,NYSE,JNJ,Pharmaceutical industry,1997-03-17,NaN,2.24%
16,JPMorgan Chase,NYSE,JPM,Financial services,1991-05-06,NaN,3.83%
17,McDonald's,NYSE,MCD,Food industry,1985-10-30,NaN,4.57%
18,Merck,NYSE,MRK,Pharmaceutical industry,1979-06-29,NaN,1.11%
19,Microsoft,NASDAQ,MSFT,Information technology,1999-11-01,NaN,6.69%
20,Nike,NYSE,NKE,Clothing industry,2013-09-23,NaN,0.90%
21,Nvidia,NASDAQ,NVDA,Information technology,2024-11-08,NaN,2.02%
22,Procter & Gamble,NYSE,PG,Fast-moving consumer goods,1932-05-26,NaN,2.46%
23,Salesforce,NYSE,CRM,Information technology,2020-08-31,NaN,3.88%
24,Sherwin-Williams,NYSE,SHW,Specialty chemicals,2024-11-08,NaN,5.19%
25,"Travelers Companies, Inc.",NYSE,TRV,Insurance,2009-06-08,NaN,3.98%
26,UnitedHealth Group,NYSE,UNH,Managed health care,2012-09-24,NaN,4.34%
27,Verizon,NYSE,VZ,Telecommunications industry,2004-04-08,NaN,0.63%
28,Visa,NYSE,V,Financial services,2013-09-23,NaN,5.28%
29,Walmart,NASDAQ,WMT,Retailing,1997-03-17,NaN,1.41%

In [8]:
data=data[['Company','Exchange','Symbol','Industry','Date added']]
data

,Company,Exchange,Symbol,Industry,Date added
0,3M,NYSE,MMM,Conglomerate,1976-08-09
1,American Express,NYSE,AXP,Financial services,1982-08-30
2,Amgen,NASDAQ,AMGN,Biopharmaceutical,2020-08-31
3,Amazon,NASDAQ,AMZN,Retailing,2024-02-26
4,Apple,NASDAQ,AAPL,Information technology,2015-03-19
5,Boeing,NYSE,BA,Aerospace and defense,1987-03-12
6,Caterpillar,NYSE,CAT,Construction and mining,1991-05-06
7,Chevron,NYSE,CVX,Petroleum industry,2008-02-19
8,Cisco,NASDAQ,CSCO,Information technology,2009-06-08
9,Coca-Cola,NYSE,KO,Drink industry,1987-03-12
10,Disney,NYSE,DIS,Broadcasting and entertainment,1991-05-06
11,Goldman Sachs,NYSE,GS,Financial services,2013-09-23
12,Home Depot,NYSE,HD,Home Improvement,1999-11-01
13,Honeywell,NASDAQ,HON,Conglomerate,2020-08-31
14,IBM,NYSE,IBM,Information technology,1979-06-29
15,Johnson & Johnson,NYSE,JNJ,Pharmaceutical industry,1997-03-17
16,JPMorgan Chase,NYSE,JPM,Financial services,1991-05-06
17,McDonald's,NYSE,MCD,Food industry,1985-10-30
18,Merck,NYSE,MRK,Pharmaceutical industry,1979-06-29
19,Microsoft,NASDAQ,MSFT,Information technology,1999-11-01
20,Nike,NYSE,NKE,Clothing industry,2013-09-23
21,Nvidia,NASDAQ,NVDA,Information technology,2024-11-08
22,Procter & Gamble,NYSE,PG,Fast-moving consumer goods,1932-05-26
23,Salesforce,NYSE,CRM,Information technology,2020-08-31
24,Sherwin-Williams,NYSE,SHW,Specialty chemicals,2024-11-08
25,"Travelers Companies, Inc.",NYSE,TRV,Insurance,2009-06-08
26,UnitedHealth Group,NYSE,UNH,Managed health care,2012-09-24
27,Verizon,NYSE,VZ,Telecommunications industry,2004-04-08
28,Visa,NYSE,V,Financial services,2013-09-23
29,Walmart,NASDAQ,WMT,Retailing,1997-03-17

In [9]:
data.loc[27:29,'Company':'Symbol']

    Company Exchange Symbol
27  Verizon     NYSE     VZ
28     Visa     NYSE      V
29  Walmart   NASDAQ    WMT

In [10]:
 data.set_index('Symbol')

,Company,Exchange,Industry,Date added
Symbol,,,,
MMM,3M,NYSE,Conglomerate,1976-08-09
AXP,American Express,NYSE,Financial services,1982-08-30
AMGN,Amgen,NASDAQ,Biopharmaceutical,2020-08-31
AMZN,Amazon,NASDAQ,Retailing,2024-02-26
AAPL,Apple,NASDAQ,Information technology,2015-03-19
BA,Boeing,NYSE,Aerospace and defense,1987-03-12
CAT,Caterpillar,NYSE,Construction and mining,1991-05-06
CVX,Chevron,NYSE,Petroleum industry,2008-02-19
CSCO,Cisco,NASDAQ,Information technology,2009-06-08
KO,Coca-Cola,NYSE,Drink industry,1987-03-12
DIS,Disney,NYSE,Broadcasting and entertainment,1991-05-06
GS,Goldman Sachs,NYSE,Financial services,2013-09-23
HD,Home Depot,NYSE,Home Improvement,1999-11-01
HON,Honeywell,NASDAQ,Conglomerate,2020-08-31
IBM,IBM,NYSE,Information technology,1979-06-29
JNJ,Johnson & Johnson,NYSE,Pharmaceutical industry,1997-03-17
JPM,JPMorgan Chase,NYSE,Financial services,1991-05-06
MCD,McDonald's,NYSE,Food industry,1985-10-30
MRK,Merck,NYSE,Pharmaceutical industry,1979-06-29
MSFT,Microsoft,NASDAQ,Information technology,1999-11-01
NKE,Nike,NYSE,Clothing industry,2013-09-23
NVDA,Nvidia,NASDAQ,Information technology,2024-11-08
PG,Procter & Gamble,NYSE,Fast-moving consumer goods,1932-05-26
CRM,Salesforce,NYSE,Information technology,2020-08-31
SHW,Sherwin-Williams,NYSE,Specialty chemicals,2024-11-08
TRV,"Travelers Companies, Inc.",NYSE,Insurance,2009-06-08
UNH,UnitedHealth Group,NYSE,Managed health care,2012-09-24
VZ,Verizon,NYSE,Telecommunications industry,2004-04-08
V,Visa,NYSE,Financial services,2013-09-23
WMT,Walmart,NASDAQ,Retailing,1997-03-17

In [12]:
data.iloc[[0,1,2],[0,1,2]]

            Company Exchange Symbol
0                3M     NYSE    MMM
1  American Express     NYSE    AXP
2             Amgen   NASDAQ   AMGN

In [21]:
df=pd.read_csv("sp500 (1).csv")
df

                           Name                  Sector   Price    EPS
0                     Apple Inc  Information Technology  170.12   9.20
1                    Abbvie Inc             Health Care   93.29   5.31
2           Abbott Laboratories             Health Care   55.28   2.41
3                 Accenture Plc  Information Technology  145.30    NaN
4                  Allergan Plc             Health Care  171.81  15.42
..                          ...                     ...     ...    ...
97   Verizon Communications Inc      Telecommunications   45.85   3.75
98     Walgreens Boots Alliance        Consumer Staples   70.25   5.10
99        Wells Fargo & Company              Financials   54.02   4.14
100             Wal-Mart Stores        Consumer Staples   96.08   4.36
101            Exxon Mobil Corp                  Energy   80.31   3.56

[102 rows x 4 columns]

In [22]:
df=df[df['Price']>100]
df

                               Name                  Sector    Price    EPS
0                         Apple Inc  Information Technology   170.12   9.20
3                     Accenture Plc  Information Technology   145.30    NaN
4                      Allergan Plc             Health Care   171.81  15.42
6                     Allstate Corp              Financials   100.50   6.79
7                             Amgen             Health Care   168.93  12.58
8                   Amazon.Com Inc.  Consumer Discretionary  1126.82   3.94
10                   Boeing Company             Industrials   265.04   9.75
12                       Biogen Inc             Health Care   311.92  21.59
14                        Blackrock              Financials   474.05  21.55
16             Berkshire Hath Hld B              Financials   181.27   6.29
18                  Caterpillar Inc             Industrials   137.37   5.55
19                     Celgene Corp             Health Care   102.88   6.40
20             Charter Communicatio  Consumer Discretionary   346.20   1.61
25                 Costco Wholesale        Consumer Staples   171.22   5.82
28                     Chevron Corp                  Energy   114.84   3.57
30              Walt Disney Company  Consumer Discretionary   103.02   5.70
36                     Facebook Inc  Information Technology   179.14   5.19
37                       Fedex Corp             Industrials   217.75  11.91
40            General Dynamics Corp             Industrials   198.70  10.07
44                 Alphabet Class C  Information Technology  1018.48  29.87
45                 Alphabet Class A  Information Technology  1034.09  29.87
46              Goldman Sachs Group              Financials   238.05  19.20
48                       Home Depot  Consumer Discretionary   170.13   6.96
49      Honeywell International Inc             Industrials   148.04   6.95
50  International Business Machines  Information Technology   151.40  13.66
52                Johnson & Johnson             Health Care   138.54   7.14
58             Lockheed Martin Corp             Industrials   312.93  12.72
60                   Mastercard Inc  Information Technology   149.93   4.31
61                  McDonald's Corp  Consumer Discretionary   167.01   6.40
65                       3M Company             Industrials   232.49   8.95
67                 Monsanto Company               Materials   118.19   5.53
71                   Nextera Energy               Utilities   155.70   6.67
75                  Priceline Group  Consumer Discretionary  1762.23  74.45
76                      Pepsico Inc        Consumer Staples   115.50   5.12
79  Philip Morris International Inc        Consumer Staples   103.35   4.49
82                 Raytheon Company             Industrials   184.22   7.56
86             Simon Property Group             Real Estate   159.25   6.05
91           Unitedhealth Group Inc             Health Care   209.75   9.60
92               Union Pacific Corp             Industrials   115.58   5.66
93            United Parcel Service             Industrials   113.20   5.98
95         United Technologies Corp             Industrials   117.05   6.62
96                         Visa Inc  Information Technology   110.27   3.48

In [24]:
df.iloc[-3:,[0,2]]

                        Name   Price
93     United Parcel Service  113.20
95  United Technologies Corp  117.05
96                  Visa Inc  110.27