In [37]:
import pandas as pd
import requests
url = 'https://en.wikipedia.org/wiki/Dow_Jones_Industrial_Average'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}

response = requests.get(url, headers=headers)
df1 = pd.read_html(response.text)
data=df1[1]
data

C:\Users\tusha\AppData\Local\Temp\ipykernel_32620\807529887.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df1 = pd.read_html(response.text)

,Company,Exchange,Symbol,Sector,Date added,Notes,Index weighting
0,3M,NYSE,MMM,Industrials,1976-08-09,As Minnesota Mining and Manufacturing,2.17%
1,American Express,NYSE,AXP,Financials,1982-08-30,NaN,4.31%
2,Amgen,NASDAQ,AMGN,Health Care,2020-08-31,NaN,4.14%
3,Amazon,NASDAQ,AMZN,Consumer Discretionary,2024-02-26,NaN,2.99%
4,Apple,NASDAQ,AAPL,Information Technology,2015-03-19,NaN,2.92%
5,Boeing,NYSE,BA,Industrials,1987-03-12,NaN,3.03%
6,Caterpillar,NYSE,CAT,Industrials,1991-05-06,NaN,5.13%
7,Chevron,NYSE,CVX,Energy,2008-02-19,Also 1930-07-18 to 1999-11-01,2.01%
8,Cisco,NASDAQ,CSCO,Information Technology,2009-06-08,NaN,0.92%
9,Coca-Cola,NYSE,KO,Consumer Staples,1987-03-12,Also 1932-05-26 to 1935-11-20,1.04%
10,Disney,NYSE,DIS,Communication Services,1991-05-06,NaN,1.63%
11,Goldman Sachs,NYSE,GS,Financials,2013-09-23,NaN,8.79%
12,Home Depot,NYSE,HD,Consumer Discretionary,1999-11-01,NaN,5.35%
13,Honeywell,NASDAQ,HON,Industrials,2020-08-31,AlliedSignal and Honeywell,3.27%
14,IBM,NYSE,IBM,Information Technology,1979-06-29,Also 1932-05-26 to 1939-03-04,3.77%
15,Johnson & Johnson,NYSE,JNJ,Health Care,1997-03-17,NaN,2.24%
16,JPMorgan Chase,NYSE,JPM,Financials,1991-05-06,NaN,3.83%
17,McDonald's,NYSE,MCD,Consumer Discretionary,1985-10-30,NaN,4.57%
18,Merck,NYSE,MRK,Health Care,1979-06-29,NaN,1.11%
19,Microsoft,NASDAQ,MSFT,Information Technology,1999-11-01,NaN,6.69%
20,Nike,NYSE,NKE,Consumer Discretionary,2013-09-23,NaN,0.90%
21,Nvidia,NASDAQ,NVDA,Information Technology,2024-11-08,NaN,2.02%
22,Procter & Gamble,NYSE,PG,Consumer Staples,1932-05-26,NaN,2.46%
23,Salesforce,NYSE,CRM,Information Technology,2020-08-31,NaN,3.88%
24,Sherwin-Williams,NYSE,SHW,Materials,2024-11-08,NaN,5.19%
25,"Travelers Companies, Inc.",NYSE,TRV,Financials,2009-06-08,NaN,3.98%
26,UnitedHealth Group,NYSE,UNH,Health Care,2012-09-24,NaN,4.34%
27,Verizon,NYSE,VZ,Communication Services,2004-04-08,NaN,0.63%
28,Visa,NYSE,V,Financials,2013-09-23,NaN,5.28%
29,Walmart,NASDAQ,WMT,Consumer Staples,1997-03-17,NaN,1.41%

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Company          30 non-null     object
 1   Exchange         30 non-null     object
 2   Symbol           30 non-null     object
 3   Sector           30 non-null     object
 4   Date added       30 non-null     object
 5   Notes            5 non-null      object
 6   Index weighting  30 non-null     object
dtypes: object(7)
memory usage: 1.8+ KB

In [39]:
a='1.35%'
float(a.replace('%',''))

1.35

In [40]:
l1=[]
for i in data['Index weighting']:
    l1.append(float(i.replace('%',"")))
data['Index weighting']=l1
data

,Company,Exchange,Symbol,Sector,Date added,Notes,Index weighting
0,3M,NYSE,MMM,Industrials,1976-08-09,As Minnesota Mining and Manufacturing,2.17
1,American Express,NYSE,AXP,Financials,1982-08-30,NaN,4.31
2,Amgen,NASDAQ,AMGN,Health Care,2020-08-31,NaN,4.14
3,Amazon,NASDAQ,AMZN,Consumer Discretionary,2024-02-26,NaN,2.99
4,Apple,NASDAQ,AAPL,Information Technology,2015-03-19,NaN,2.92
5,Boeing,NYSE,BA,Industrials,1987-03-12,NaN,3.03
6,Caterpillar,NYSE,CAT,Industrials,1991-05-06,NaN,5.13
7,Chevron,NYSE,CVX,Energy,2008-02-19,Also 1930-07-18 to 1999-11-01,2.01
8,Cisco,NASDAQ,CSCO,Information Technology,2009-06-08,NaN,0.92
9,Coca-Cola,NYSE,KO,Consumer Staples,1987-03-12,Also 1932-05-26 to 1935-11-20,1.04
10,Disney,NYSE,DIS,Communication Services,1991-05-06,NaN,1.63
11,Goldman Sachs,NYSE,GS,Financials,2013-09-23,NaN,8.79
12,Home Depot,NYSE,HD,Consumer Discretionary,1999-11-01,NaN,5.35
13,Honeywell,NASDAQ,HON,Industrials,2020-08-31,AlliedSignal and Honeywell,3.27
14,IBM,NYSE,IBM,Information Technology,1979-06-29,Also 1932-05-26 to 1939-03-04,3.77
15,Johnson & Johnson,NYSE,JNJ,Health Care,1997-03-17,NaN,2.24
16,JPMorgan Chase,NYSE,JPM,Financials,1991-05-06,NaN,3.83
17,McDonald's,NYSE,MCD,Consumer Discretionary,1985-10-30,NaN,4.57
18,Merck,NYSE,MRK,Health Care,1979-06-29,NaN,1.11
19,Microsoft,NASDAQ,MSFT,Information Technology,1999-11-01,NaN,6.69
20,Nike,NYSE,NKE,Consumer Discretionary,2013-09-23,NaN,0.90
21,Nvidia,NASDAQ,NVDA,Information Technology,2024-11-08,NaN,2.02
22,Procter & Gamble,NYSE,PG,Consumer Staples,1932-05-26,NaN,2.46
23,Salesforce,NYSE,CRM,Information Technology,2020-08-31,NaN,3.88
24,Sherwin-Williams,NYSE,SHW,Materials,2024-11-08,NaN,5.19
25,"Travelers Companies, Inc.",NYSE,TRV,Financials,2009-06-08,NaN,3.98
26,UnitedHealth Group,NYSE,UNH,Health Care,2012-09-24,NaN,4.34
27,Verizon,NYSE,VZ,Communication Services,2004-04-08,NaN,0.63
28,Visa,NYSE,V,Financials,2013-09-23,NaN,5.28
29,Walmart,NASDAQ,WMT,Consumer Staples,1997-03-17,NaN,1.41

In [41]:
data['Date added'].str.replace('-',"*")

0     1976*08*09
1     1982*08*30
2     2020*08*31
3     2024*02*26
4     2015*03*19
5     1987*03*12
6     1991*05*06
7     2008*02*19
8     2009*06*08
9     1987*03*12
10    1991*05*06
11    2013*09*23
12    1999*11*01
13    2020*08*31
14    1979*06*29
15    1997*03*17
16    1991*05*06
17    1985*10*30
18    1979*06*29
19    1999*11*01
20    2013*09*23
21    2024*11*08
22    1932*05*26
23    2020*08*31
24    2024*11*08
25    2009*06*08
26    2012*09*24
27    2004*04*08
28    2013*09*23
29    1997*03*17
Name: Date added, dtype: object

In [45]:
data['Date added']=data['Date added'].str.replace('-',"*")

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Company          30 non-null     object
 1   Exchange         30 non-null     object
 2   Symbol           30 non-null     object
 3   Sector           30 non-null     object
 4   Date added       30 non-null     object
 5   Notes            5 non-null      object
 6   Index weighting  30 non-null     float64
dtypes: float64(1), object(6)
memory usage: 1.8+ KB