In [1]:
import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies" 
""

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print(response.status_code)

tables = pd.read_html(response.text)
data=tables[0]
data

200

C:\Users\tusha\AppData\Local\Temp\ipykernel_26324\838413954.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [2]:
data=data.set_index('Symbol')

In [3]:
data1=data[['Security','GICS Sector','GICS Sub-Industry']]
data1

,Security,GICS Sector,GICS Sub-Industry
Symbol,,,
MMM,3M,Industrials,Industrial Conglomerates
AOS,A. O. Smith,Industrials,Building Products
ABT,Abbott Laboratories,Health Care,Health Care Equipment
ABBV,AbbVie,Health Care,Biotechnology
ACN,Accenture,Information Technology,IT Consulting & Other Services
...,...,...,...
XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components
YUM,Yum! Brands,Consumer Discretionary,Restaurants
ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments
ZBH,Zimmer Biomet,Health Care,Health Care Equipment
ZTS,Zoetis,Health Care,Pharmaceuticals

In [4]:
data2=data.iloc[:,-3:]
data2

        Date added      CIK      Founded
Symbol
MMM     1957-03-04    66740         1902
AOS     2017-07-26    91142         1916
ABT     1957-03-04     1800         1888
ABBV    2012-12-31  1551152  2013 (1888)
ACN     2011-07-06  1467373         1989
...            ...      ...          ...
XYL     2011-11-01  1524472         2011
YUM     1997-10-06  1041061         1997
ZBRA    2019-12-23   877212         1969
ZBH     2001-08-07  1136869         1927
ZTS     2013-06-21  1555280         1952

[503 rows x 3 columns]

In [5]:
pd.merge(data1,data2,on='Symbol')

,Security,GICS Sector,GICS Sub-Industry,Date added,CIK,Founded
Symbol,,,,,,
MMM,3M,Industrials,Industrial Conglomerates,1957-03-04,66740,1902
AOS,A. O. Smith,Industrials,Building Products,2017-07-26,91142,1916
ABT,Abbott Laboratories,Health Care,Health Care Equipment,1957-03-04,1800,1888
ABBV,AbbVie,Health Care,Biotechnology,2012-12-31,1551152,2013 (1888)
ACN,Accenture,Information Technology,IT Consulting & Other Services,2011-07-06,1467373,1989
...,...,...,...,...,...,...
XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,2011-11-01,1524472,2011
YUM,Yum! Brands,Consumer Discretionary,Restaurants,1997-10-06,1041061,1997
ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,2019-12-23,877212,1969
ZBH,Zimmer Biomet,Health Care,Health Care Equipment,2001-08-07,1136869,1927
ZTS,Zoetis,Health Care,Pharmaceuticals,2013-06-21,1555280,1952

In [7]:
import numpy as np
np1=np.random.randint(100,200,25).reshape(5,5)
df1=pd.DataFrame(np1,index=['r1','r2','r3','r4','r5'],columns=['cr1','cr2','cr3','cr4','cr5'])
df1

    cr1  cr2  cr3  cr4  cr5
r1  158  158  119  131  107
r2  141  120  169  152  120
r3  149  152  182  155  131
r4  163  165  181  162  112
r5  131  195  129  128  188

In [9]:

np1=np.random.randint(100,200,25).reshape(5,5)
df2=pd.DataFrame(np1,index=['r1','r2','r3','r4','r5'],columns=['c1','c2','c3','c4','c5'])
df2

     c1   c2   c3   c4   c5
r1  129  142  102  187  108
r2  162  162  161  134  151
r3  121  133  126  110  135
r4  130  155  164  141  118
r5  169  100  153  158  151

In [10]:
df1.index.name='i1'
df2.index.name='i1'
pd.merge(df1,df2,on='i1')

    cr1  cr2  cr3  cr4  cr5   c1   c2   c3   c4   c5
i1
r1  158  158  119  131  107  129  142  102  187  108
r2  141  120  169  152  120  162  162  161  134  151
r3  149  152  182  155  131  121  133  126  110  135
r4  163  165  181  162  112  130  155  164  141  118
r5  131  195  129  128  188  169  100  153  158  151

##DELETe row and column use drop ,axis function

In [12]:
data.drop('AOS',axis=0)

,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
Symbol,,,,,,,
MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
ADBE,Adobe Inc.,Information Technology,Application Software,"San Jose, California",1997-05-05,796343,1982
...,...,...,...,...,...,...,...
XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [13]:
data.drop(['ZBRA','ZBH','ZTS'],axis=0)

,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
Symbol,,,,,,,
MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...
WDAY,"Workday, Inc.",Information Technology,Application Software,"Pleasanton, California",2024-12-23,1327811,2005
WYNN,Wynn Resorts,Consumer Discretionary,Casinos & Gaming,"Paradise, Nevada",2008-11-14,1174922,2002
XEL,Xcel Energy,Utilities,Multi-Utilities,"Minneapolis, Minnesota",1957-03-04,72903,1909
XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997