Readcsv function

In [2]:
import pandas as pd
df1=pd.read_csv(r'D:\github page\1_numpy&pandas\data.csv')
df1

,Date,SP500,Dividend,Earnings,Consumer Price Index,Long Interest Rate,Real Price,Real Dividend,Real Earnings,PE10
0,1871-01-01,4.44,0.26,0.4,12.46,5.32,109.05,6.39,9.82,0.0
1,1871-02-01,4.50,0.26,0.4,12.84,5.32,107.25,6.20,9.53,0.0
2,1871-03-01,4.61,0.26,0.4,13.03,5.33,108.27,6.11,9.39,0.0
3,1871-04-01,4.74,0.26,0.4,12.56,5.33,115.54,6.34,9.75,0.0
4,1871-05-01,4.86,0.26,0.4,12.27,5.33,121.22,6.48,9.98,0.0
...,...,...,...,...,...,...,...,...,...,...
1861,2026-02-01,6893.81,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0
1862,2026-03-01,6654.42,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0
1863,2026-04-01,6957.01,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0
1864,2026-05-01,7412.55,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0
1865,2026-06-01,7450.03,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.0

In [3]:
df2=pd.read_csv(r'D:\github page\1_numpy&pandas\constituents.csv')
df2

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [4]:
dff1=pd.read_excel(r'D:\github page\1_numpy&pandas\Complete-List-of-SP-500-Index-Companies-July-4-2026.xlsx')
dff1

     S.No.          Company Name Ticker                  Sector
0        1             Apple Inc   AAPL  Information Technology
1        2        Microsoft Corp   MSFT  Information Technology
2        3        Amazon Com Inc   AMZN  Consumer Discretionary
3        4           Nvidia Corp   NVDA  Information Technology
4        5  Alphabet Inc Class A  GOOGL           Communication
..     ...                   ...    ...                     ...
499    500      Fox Corp Class B    FOX           Communication
500    501        Blackstone Inc     BX              Financials
501    502            Airbnb Inc   ABNB  Consumer Discretionary
502    503     News Corp Class B    NWS           Communication
503    504    Expand Energy Corp    EXE                  Energy

[504 rows x 4 columns]

Read html use data from other sites

In [5]:
import pandas as pd
import requests

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
    "Accept-Language": "en-US,en;q=0.9",
}

session = requests.Session()
session.headers.update(headers)

# NSE requires you to visit the homepage first to get valid cookies
session.get("https://www.nseindia.com", timeout=5)

url = "https://archives.nseindia.com/content/indices/ind_nifty50list.csv"
response = session.get(url, timeout=5)
response.raise_for_status()

with open("nifty50list.csv", "wb") as f:
    f.write(response.content)

df3 = pd.read_csv("nifty50list.csv")
df3

,Company Name,Industry,Symbol,Series,ISIN Code
0,Adani Enterprises Ltd.,Metals & Mining,ADANIENT,EQ,INE423A01024
1,Adani Ports and Special Economic Zone Ltd.,Services,ADANIPORTS,EQ,INE742F01042
2,Apollo Hospitals Enterprise Ltd.,Healthcare,APOLLOHOSP,EQ,INE437A01024
3,Asian Paints Ltd.,Consumer Durables,ASIANPAINT,EQ,INE021A01026
4,Axis Bank Ltd.,Financial Services,AXISBANK,EQ,INE238A01034
5,Bajaj Auto Ltd.,Automobile and Auto Components,BAJAJ-AUTO,EQ,INE917I01010
6,Bajaj Finance Ltd.,Financial Services,BAJFINANCE,EQ,INE296A01032
7,Bajaj Finserv Ltd.,Financial Services,BAJAJFINSV,EQ,INE918I01026
8,Bharat Electronics Ltd.,Capital Goods,BEL,EQ,INE263A01024
9,Bharti Airtel Ltd.,Telecommunication,BHARTIARTL,EQ,INE397D01024
10,Cipla Ltd.,Healthcare,CIPLA,EQ,INE059A01026
11,Coal India Ltd.,Oil Gas & Consumable Fuels,COALINDIA,EQ,INE522F01014
12,Dr. Reddy's Laboratories Ltd.,Healthcare,DRREDDY,EQ,INE089A01031
13,Eicher Motors Ltd.,Automobile and Auto Components,EICHERMOT,EQ,INE066A01021
14,Eternal Ltd.,Consumer Services,ETERNAL,EQ,INE758T01015
15,Grasim Industries Ltd.,Construction Materials,GRASIM,EQ,INE047A01021
16,HCL Technologies Ltd.,Information Technology,HCLTECH,EQ,INE860A01027
17,HDFC Bank Ltd.,Financial Services,HDFCBANK,EQ,INE040A01034
18,HDFC Life Insurance Company Ltd.,Financial Services,HDFCLIFE,EQ,INE795G01014
19,Hindalco Industries Ltd.,Metals & Mining,HINDALCO,EQ,INE038A01020
20,Hindustan Unilever Ltd.,Fast Moving Consumer Goods,HINDUNILVR,EQ,INE030A01027
21,ICICI Bank Ltd.,Financial Services,ICICIBANK,EQ,INE090A01021
22,ITC Ltd.,Fast Moving Consumer Goods,ITC,EQ,INE154A01025
23,Infosys Ltd.,Information Technology,INFY,EQ,INE009A01021
24,InterGlobe Aviation Ltd.,Services,INDIGO,EQ,INE646L01027
25,JSW Steel Ltd.,Metals & Mining,JSWSTEEL,EQ,INE019A01038
26,Jio Financial Services Ltd.,Financial Services,JIOFIN,EQ,INE758E01017
27,Kotak Mahindra Bank Ltd.,Financial Services,KOTAKBANK,EQ,INE237A01036
28,Larsen & Toubro Ltd.,Construction,LT,EQ,INE018A01030
29,Mahindra & Mahindra Ltd.,Automobile and Auto Components,M&M,EQ,INE101A01026
30,Maruti Suzuki India Ltd.,Automobile and Auto Components,MARUTI,EQ,INE585B01010
31,Max Healthcare Institute Ltd.,Healthcare,MAXHEALTH,EQ,INE027H01010
32,NTPC Ltd.,Power,NTPC,EQ,INE733E01010
33,Nestle India Ltd.,Fast Moving Consumer Goods,NESTLEIND,EQ,INE239A01024
34,Oil & Natural Gas Corporation Ltd.,Oil Gas & Consumable Fuels,ONGC,EQ,INE213A01029
35,Power Grid Corporation of India Ltd.,Power,POWERGRID,EQ,INE752E01010
36,Reliance Industries Ltd.,Oil Gas & Consumable Fuels,RELIANCE,EQ,INE002A01018
37,SBI Life Insurance Company Ltd.,Financial Services,SBILIFE,EQ,INE123W01016
38,Shriram Finance Ltd.,Financial Services,SHRIRAMFIN,EQ,INE721A01047
39,State Bank of India,Financial Services,SBIN,EQ,INE062A01020
40,Sun Pharmaceutical Industries Ltd.,Healthcare,SUNPHARMA,EQ,INE044A01036
41,Tata Consultancy Services Ltd.,Information Technology,TCS,EQ,INE467B01029
42,Tata Consumer Products Ltd.,Fast Moving Consumer Goods,TATACONSUM,EQ,INE192A01025
43,Tata Motors Passenger Vehicles Ltd.,Automobile and Auto Components,TMPV,EQ,INE155A01022
44,Tata Steel Ltd.,Metals & Mining,TATASTEEL,EQ,INE081A01020
45,Tech Mahindra Ltd.,Information Technology,TECHM,EQ,INE669C01036
46,Titan Company Ltd.,Consumer Durables,TITAN,EQ,INE280A01028
47,Trent Ltd.,Consumer Services,TRENT,EQ,INE849A01020
48,UltraTech Cement Ltd.,Construction Materials,ULTRACEMCO,EQ,INE481G01011
49,Wipro Ltd.,Information Technology,WIPRO,EQ,INE075A01022

In [6]:
df3.head(10)
df3.info()
df3.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Company Name  50 non-null     object
 1   Industry      50 non-null     object
 2   Symbol        50 non-null     object
 3   Series        50 non-null     object
 4   ISIN Code     50 non-null     object
dtypes: object(5)
memory usage: 2.1+ KB

,Company Name,Industry,Symbol,Series,ISIN Code
count,50,50,50,50,50
unique,50,15,50,1,50
top,Adani Enterprises Ltd.,Financial Services,ADANIENT,EQ,INE423A01024
freq,1,11,1,50,1

In [8]:
df3.index
df3.columns

Index(['Company Name', 'Industry', 'Symbol', 'Series', 'ISIN Code'], dtype='object')

Subseting-where i need only one and two column ,here we use square bracket and list for using more than one column

In [13]:
df3[['Symbol','Industry']]

        Symbol                        Industry
0     ADANIENT                 Metals & Mining
1   ADANIPORTS                        Services
2   APOLLOHOSP                      Healthcare
3   ASIANPAINT               Consumer Durables
4     AXISBANK              Financial Services
5   BAJAJ-AUTO  Automobile and Auto Components
6   BAJFINANCE              Financial Services
7   BAJAJFINSV              Financial Services
8          BEL                   Capital Goods
9   BHARTIARTL               Telecommunication
10       CIPLA                      Healthcare
11   COALINDIA      Oil Gas & Consumable Fuels
12     DRREDDY                      Healthcare
13   EICHERMOT  Automobile and Auto Components
14     ETERNAL               Consumer Services
15      GRASIM          Construction Materials
16     HCLTECH          Information Technology
17    HDFCBANK              Financial Services
18    HDFCLIFE              Financial Services
19    HINDALCO                 Metals & Mining
20  HINDUNILVR      Fast Moving Consumer Goods
21   ICICIBANK              Financial Services
22         ITC      Fast Moving Consumer Goods
23        INFY          Information Technology
24      INDIGO                        Services
25    JSWSTEEL                 Metals & Mining
26      JIOFIN              Financial Services
27   KOTAKBANK              Financial Services
28          LT                    Construction
29         M&M  Automobile and Auto Components
30      MARUTI  Automobile and Auto Components
31   MAXHEALTH                      Healthcare
32        NTPC                           Power
33   NESTLEIND      Fast Moving Consumer Goods
34        ONGC      Oil Gas & Consumable Fuels
35   POWERGRID                           Power
36    RELIANCE      Oil Gas & Consumable Fuels
37     SBILIFE              Financial Services
38  SHRIRAMFIN              Financial Services
39        SBIN              Financial Services
40   SUNPHARMA                      Healthcare
41         TCS          Information Technology
42  TATACONSUM      Fast Moving Consumer Goods
43        TMPV  Automobile and Auto Components
44   TATASTEEL                 Metals & Mining
45       TECHM          Information Technology
46       TITAN               Consumer Durables
47       TRENT               Consumer Services
48  ULTRACEMCO          Construction Materials
49       WIPRO          Information Technology

how to filter a data in data frame

In [26]:
import pandas as pd
import requests

url = "https://www.screener.in/screens/281185/nifty-50/" 
""

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print(response.status_code)

tables = pd.read_html(response.text)
data=tables[0]
data

200

C:\Users\tusha\AppData\Local\Temp\ipykernel_20216\3327289715.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
0,1.,Reliance Industries,1323.10,23.97,1791434.55,0.45,23196.00,2.02,309468.00,27.02,10.26
1,2.,HDFC Bank,777.60,15.16,1197534.17,1.67,20382.69,18.37,90575.33,3.67,7.02
2,3.,ICICI Bank,1460.20,18.71,1049327.96,0.82,16276.22,13.88,52240.85,6.44,7.59
3,4.,TCS,2251.10,15.17,814736.99,2.84,13420.00,8.45,72275.00,13.93,63.03
4,5.,Axis Bank,1256.00,14.06,390605.10,0.08,7670.37,22.24,35541.96,9.87,6.24
5,6.,Kotak Mah. Bank,382.05,18.98,380136.78,0.17,5480.46,22.55,18354.57,6.41,6.98
6,7.,UltraTech Cem.,11903.00,40.67,350799.99,0.65,2603.72,15.75,24648.20,15.85,12.78
7,8.,HCL Technologies,1221.30,18.28,331433.68,4.42,4626.00,20.32,34579.00,13.94,30.60
8,9.,JSW Steel,1257.00,25.51,307132.92,0.56,4696.00,112.96,47364.00,9.77,10.96
9,10.,Avenue Super.,3975.50,84.83,259428.40,0.00,860.44,11.34,18794.53,14.88,17.19
10,11.,Wipro,176.38,13.21,174684.70,6.24,3356.30,0.65,24478.60,10.59,17.84
11,12.,Jio Financial,238.92,76.34,157749.28,0.21,830.25,174.44,2004.47,227.28,1.86
12,13.,Tech Mahindra,1576.40,29.08,154732.44,3.24,1486.30,28.45,15711.90,17.68,23.12
13,14.,ICICI AMC,3117.40,44.10,153727.56,0.87,964.63,23.10,1564.22,17.55,115.10
14,15.,B H E L,417.50,59.78,145410.60,0.34,376.71,182.70,7697.72,40.29,9.14
15,S.No.,Name,CMP Rs.,P/E,Mar Cap Rs.Cr.,Div Yld %,NP Qtr Rs.Cr.,Qtr Profit Var %,Sales Qtr Rs.Cr.,Qtr Sales Var %,ROCE %
16,16.,Union Bank (I),175.93,6.50,134226.31,2.84,5641.52,27.41,27427.10,1.21,6.30
17,17.,Polycab India,8885.00,46.71,133779.86,0.53,796.66,32.46,8209.73,39.01,33.21
18,18.,Punjab Natl.Bank,111.76,5.81,128408.71,2.68,5834.77,174.29,33589.17,3.12,6.13
19,19.,Billionbrains,203.43,52.32,127654.42,0.00,735.04,94.28,1501.42,66.01,37.32
20,20.,HDFC Life Insur.,564.65,62.12,122690.56,0.37,611.19,11.46,33758.51,14.58,10.30
21,21.,LTM,4083.90,21.61,121207.07,1.84,1468.60,16.92,11608.00,17.96,29.60
22,22.,Indian Bank,858.50,9.03,115470.39,2.13,3357.44,20.47,18095.14,11.11,6.32
23,23.,HDFC AMC,2644.90,38.42,113342.43,2.04,838.36,12.09,1098.50,13.51,42.88
24,24.,IDBI Bank,85.03,9.81,91427.67,2.47,2130.57,5.35,7549.28,7.44,5.92
25,25.,Federal Bank,350.75,18.50,86647.21,0.34,1302.49,36.78,7861.58,9.94,6.39