In [14]:
import pandas as pd
df=pd.read_csv(r'D:\github page\1_numpy&pandas\unicorn.csv')
df

,Company,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding
0,Bytedance,180,07-04-2017,Artificial intelligence,Beijing,China,Asia,2012,NaN
1,SpaceX,100,01-12-2012,Other,Hawthorne,United States,North America,2002,7.0
2,SHEIN,100,03-07-2018,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,2.0
3,Stripe,95,23-01-2014,Fintech,San Francisco,United States,North America,2010,2.0
4,Klarna,46,12-12-2011,Fintech,Stockholm,Sweden,Europe,2005,4.0
...,...,...,...,...,...,...,...,...,...
1069,Zhaogang,1,29-06-2017,E-commerce & direct-to-consumer,Shanghai,China,Asia,2012,379.0
1070,Zhuan Zhuan,1,18-04-2017,E-commerce & direct-to-consumer,Beijing,China,Asia,2015,990.0
1071,Zihaiguo,1,06-05-2021,Consumer & retail,Chongqing,China,Asia,2018,80.0
1072,Zopa,1,19-10-2021,Fintech,London,United Kingdom,Europe,2005,792.0
1073,Zwift,1,16-09-2020,E-commerce & direct-to-consumer,Long Beach,United States,North America,2014,620.0

In [27]:
df=df.set_index('Company')

KeyError: "None of ['Company'] are in the columns"

df.reset_index to get original data back after set index

In [23]:
df[df['Country']=='United Kingdom']

,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding
Company,,,,,,,,
Checkout.com,40,02-05-2019,Fintech,London,United Kingdom,Europe,2012,2.0
Revolut,33,26-04-2018,Fintech,London,United Kingdom,Europe,2015,2.0
Rapyd,15,03-12-2019,Fintech,London,United Kingdom,Europe,2016,770.0
Blockchain.com,14,17-02-2021,Fintech,London,United Kingdom,Europe,2011,490.0
Global Switch,11,22-12-2016,Hardware,London,United Kingdom,Europe,1998,5.0
Hopin,8,10-11-2020,Internet software & services,London,United Kingdom,Europe,2019,1.0
Howden Group Holdings,5,29-09-2020,Other,London,United Kingdom,Europe,1994,187.0
Monzo,5,31-10-2018,Fintech,London,United Kingdom,Europe,2015,1.0
Lendable,5,31-03-2021,Fintech,London,United Kingdom,Europe,2014,286.0
ZEPZ,5,23-08-2021,Fintech,London,United Kingdom,Europe,2010,655.0
Greensill,4,16-07-2018,Fintech,London,United Kingdom,Europe,2011,2.0
OakNorth Bank,3,12-10-2017,Fintech,London,United Kingdom,Europe,2015,1.0
Graphcore,3,18-12-2018,Artificial intelligence,Bristol,United Kingdom,Europe,2016,682.0
CMR Surgical,3,17-09-2019,Health,Cambridge,United Kingdom,Europe,2014,975.0
Bought By Many,2,01-06-2021,Fintech,London,United Kingdom,Europe,2012,477.0
BGL Group,2,24-11-2017,Fintech,Peterborough,United Kingdom,Europe,1992,696.0
Improbable,2,11-05-2017,Other,London,United Kingdom,Europe,2012,754.0
BrewDog,2,10-04-2017,Consumer & retail,Aberdeen,United Kingdom,Europe,2007,233.0
Gett,2,24-05-2016,Auto & transportation,London,United Kingdom,Europe,2010,828.0
Matillion,2,15-09-2021,Data management & analytics,Altrincham,United Kingdom,Europe,2011,310.0
Gousto,2,03-11-2020,"Supply chain, logistics, & delivery",London,United Kingdom,Europe,2012,311.0
Accelerant,2,12-01-2022,Other,Colchester,United Kingdom,Europe,2018,193.0
GoCardless,2,08-02-2022,Fintech,London,United Kingdom,Europe,2011,529.0
PayFit,2,06-01-2022,Fintech,London,United Kingdom,Europe,2016,496.0
Starling Bank,2,08-03-2021,Fintech,London,United Kingdom,Europe,2014,791.0
Zilch,2,10-11-2021,Fintech,London,United Kingdom,Europe,2018,339.0
SumUp,1,16-07-2019,Fintech,London,United Kingdom,Europe,2011,1.0
Gymshark,1,14-08-2020,E-commerce & direct-to-consumer,Solihull,United Kingdom,Europe,2012,262.0
Tripledot,1,14-02-2022,Mobile & telecommunications,London,United Kingdom,Europe,2017,202.0
Motorway,1,29-11-2021,E-commerce & direct-to-consumer,London,United Kingdom,Europe,2017,276.0
OVO Energy,1,14-02-2019,Other,Bristol,United Kingdom,Europe,2009,324.0
Marshmallow,1,08-09-2021,Fintech,London,United Kingdom,Europe,2017,116.0
The Bank of London,1,30-11-2021,Fintech,London,United Kingdom,Europe,2018,90.0
Zego,1,09-03-2021,Fintech,London,United Kingdom,Europe,2016,202.0
Radius Payment Solutions,1,27-11-2017,Fintech,Crewe,United Kingdom,Europe,1990,200.0
BenevolentAI,1,02-06-2015,Artificial intelligence,London,United Kingdom,Europe,2013,292.0
Payhawk,1,14-02-2022,Fintech,London,United Kingdom,Europe,2018,239.0
PPRO,1,19-01-2021,Fintech,London,United Kingdom,Europe,2006,370.0
SaltPay,1,09-04-2021,Fintech,London,United Kingdom,Europe,2019,1.0
Thought Machine,1,29-11-2021,Fintech,London,United Kingdom,Europe,2014,403.0
Tractable,1,16-06-2021,Artificial intelligence,London,United Kingdom,Europe,2014,120.0
TrueLayer,1,21-09-2021,Fintech,London,United Kingdom,Europe,2016,271.0
Zopa,1,19-10-2021,Fintech,London,United Kingdom,Europe,2005,792.0

In [17]:
df[(df['Country']=='United Kingdom') & (df['Funding']>500)]

,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding
Company,,,,,,,,
Rapyd,15,03-12-2019,Fintech,London,United Kingdom,Europe,2016,770.0
ZEPZ,5,23-08-2021,Fintech,London,United Kingdom,Europe,2010,655.0
Graphcore,3,18-12-2018,Artificial intelligence,Bristol,United Kingdom,Europe,2016,682.0
CMR Surgical,3,17-09-2019,Health,Cambridge,United Kingdom,Europe,2014,975.0
BGL Group,2,24-11-2017,Fintech,Peterborough,United Kingdom,Europe,1992,696.0
Improbable,2,11-05-2017,Other,London,United Kingdom,Europe,2012,754.0
Gett,2,24-05-2016,Auto & transportation,London,United Kingdom,Europe,2010,828.0
GoCardless,2,08-02-2022,Fintech,London,United Kingdom,Europe,2011,529.0
Starling Bank,2,08-03-2021,Fintech,London,United Kingdom,Europe,2014,791.0
Zopa,1,19-10-2021,Fintech,London,United Kingdom,Europe,2005,792.0

loc and .iloc

In [18]:
df.loc['SpaceX','City']

'Hawthorne'

In [19]:
df.loc['Zopa':'Zwift','Industry':'City']

                                Industry        City
Company
Zopa                             Fintech      London
Zwift    E-commerce & direct-to-consumer  Long Beach

In [20]:
df.iloc[3,4]

'United States'

In [28]:
df

,Valuation,Date Joined,Industry,City,Country,Continent,Year Founded,Funding
Company,,,,,,,,
Bytedance,180,07-04-2017,Artificial intelligence,Beijing,China,Asia,2012,NaN
SpaceX,100,01-12-2012,Other,Hawthorne,United States,North America,2002,7.0
SHEIN,100,03-07-2018,E-commerce & direct-to-consumer,Shenzhen,China,Asia,2008,2.0
Stripe,95,23-01-2014,Fintech,San Francisco,United States,North America,2010,2.0
Klarna,46,12-12-2011,Fintech,Stockholm,Sweden,Europe,2005,4.0
...,...,...,...,...,...,...,...,...
Zhaogang,1,29-06-2017,E-commerce & direct-to-consumer,Shanghai,China,Asia,2012,379.0
Zhuan Zhuan,1,18-04-2017,E-commerce & direct-to-consumer,Beijing,China,Asia,2015,990.0
Zihaiguo,1,06-05-2021,Consumer & retail,Chongqing,China,Asia,2018,80.0
Zopa,1,19-10-2021,Fintech,London,United Kingdom,Europe,2005,792.0
Zwift,1,16-09-2020,E-commerce & direct-to-consumer,Long Beach,United States,North America,2014,620.0

In [31]:
df.iloc[1,-2]

np.int64(2002)

In [1]:
import pandas as pd
import requests

url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies" 
""

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print(response.status_code)

tables = pd.read_html(response.text)
data=tables[0]
data

200

C:\Users\tusha\AppData\Local\Temp\ipykernel_10320\2235869911.py:15: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,MMM,3M,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1957-03-04,66740,1902
1,AOS,A. O. Smith,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott Laboratories,Health Care,Health Care Equipment,"North Chicago, Illinois",1957-03-04,1800,1888
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ACN,Accenture,Information Technology,IT Consulting & Other Services,"Dublin, Ireland",2011-07-06,1467373,1989
...,...,...,...,...,...,...,...,...
498,XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components,"White Plains, New York",2011-11-01,1524472,2011
499,YUM,Yum! Brands,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
500,ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
501,ZBH,Zimmer Biomet,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZTS,Zoetis,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [12]:
data1=data[data['GICS Sub-Industry']=='Biotechnology']

In [9]:
data1.iloc[-3:,1]

318                      Moderna
391    Regeneron Pharmaceuticals
471       Vertex Pharmaceuticals
Name: Security, dtype: object

add two row column horizontaly, vertically

In [11]:
data1

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
3,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
32,AMGN,Amgen,Health Care,Biotechnology,"Thousand Oaks, California",1992-01-02,318154,1980
64,BIIB,Biogen,Health Care,Biotechnology,"Cambridge, Massachusetts",2003-11-13,875045,1978
220,GILD,Gilead Sciences,Health Care,Biotechnology,"Foster City, California",2004-07-01,882095,1987
249,INCY,Incyte,Health Care,Biotechnology,"Wilmington, Delaware",2017-02-28,879169,1991
318,MRNA,Moderna,Health Care,Biotechnology,"Cambridge, Massachusetts",2021-07-21,1682852,2010
391,REGN,Regeneron Pharmaceuticals,Health Care,Biotechnology,"Tarrytown, New York",2013-05-01,872589,1988
471,VRTX,Vertex Pharmaceuticals,Health Care,Biotechnology,"Boston, Massachusetts",2013-09-23,875320,1989

In [19]:
data1.reset_index()

,Symbol,Security,GICS Sector,GICS Sub-Industry,Headquarters Location,Date added,CIK,Founded
0,ABBV,AbbVie,Health Care,Biotechnology,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
1,AMGN,Amgen,Health Care,Biotechnology,"Thousand Oaks, California",1992-01-02,318154,1980
2,BIIB,Biogen,Health Care,Biotechnology,"Cambridge, Massachusetts",2003-11-13,875045,1978
3,GILD,Gilead Sciences,Health Care,Biotechnology,"Foster City, California",2004-07-01,882095,1987
4,INCY,Incyte,Health Care,Biotechnology,"Wilmington, Delaware",2017-02-28,879169,1991
5,MRNA,Moderna,Health Care,Biotechnology,"Cambridge, Massachusetts",2021-07-21,1682852,2010
6,REGN,Regeneron Pharmaceuticals,Health Care,Biotechnology,"Tarrytown, New York",2013-05-01,872589,1988
7,VRTX,Vertex Pharmaceuticals,Health Care,Biotechnology,"Boston, Massachusetts",2013-09-23,875320,1989

In [30]:
data1=data[['Security','GICS Sector','GICS Sub-Industry','Symbol']]
data1.set_index('Symbol')

,Security,GICS Sector,GICS Sub-Industry
Symbol,,,
MMM,3M,Industrials,Industrial Conglomerates
AOS,A. O. Smith,Industrials,Building Products
ABT,Abbott Laboratories,Health Care,Health Care Equipment
ABBV,AbbVie,Health Care,Biotechnology
ACN,Accenture,Information Technology,IT Consulting & Other Services
...,...,...,...
XYL,Xylem Inc.,Industrials,Industrial Machinery & Supplies & Components
YUM,Yum! Brands,Consumer Discretionary,Restaurants
ZBRA,Zebra Technologies,Information Technology,Electronic Equipment & Instruments
ZBH,Zimmer Biomet,Health Care,Health Care Equipment
ZTS,Zoetis,Health Care,Pharmaceuticals